### ISSUE TITLE
Emulator Support!!

### ISSUE THREAD

**Issue by Unknown6969696969** [fedes1to/Zygisk-ImGui-Menu#6]
I have found this zygisk menu very recently and it's working perfectly on my phone.
I wanted to try it on emulators because not many people have a rooted phone but it's not working as expected.
Tested on latest Nox Android 9 (x64) and latest BlueStacks Android 11 emulator and Using an arm64 game.
✓ Module is running.
✓ Attaching to the game and menu appearing.
✓ Hooking to the right address.
× Not using arm64 hooking.

Checked using GG and the game is running on arm 64bit.
I believe this is using x86_64 bit hooking methods and it's causing the crashes.
Is it possible to set hooking methods to a specific type? eg. armv7a or armv8a.
I would really appreciate if anyone help me with this 😄

**Comment by fedes1to** [comment]
The module uses Dobby for the hooks, you can try using something like A64InlineHook for hooks related to targeting arm64 devices, as dobby on x86_64 is still needed for the input symbol and egl hook.

**Comment by MrWildanMD** [comment]
@Unknown6969696969 do you found the workaround for this? Facing same problem with hooking..working perfectly on phone but not in emulator

**Comment by fedes1to** [comment]
> @Unknown6969696969 do you found the workaround for this? Facing same problem with hooking..working perfectly on phone but not in emulator

try to use a different injection method

zygisk only loads a library with a matching CPU_ABI , so it loads the x64 library instead of the one needed to target a games arch. therefore a hook being x64 and a game being armv8 will cause the game to crash. you can try calling dlopen on a proper arm64 library and calling your hack_thread there, although you probably wont have access to any jvm environments unless you use native java hook functions.
